version: '3.3'

services:
  cvat_server:
    environment:
      USE_ALLAUTH_SOCIAL_ACCOUNTS: "True"
      SOCIAL_AUTH_GOOGLE_CLIENT_ID: "XXX"
      SOCIAL_AUTH_GOOGLE_CLIENT_SECRET: "XXX"
      SOCIAL_AUTH_GITHUB_CLIENT_ID: "XXX"
      SOCIAL_AUTH_GITHUB_CLIENT_SECRET: "XXX"
      DJANGO_SETTINGS_MODULE: cvat.settings.social_auth_settings

  google_auth_server:
    image: python:3.9-slim
    restart: always
    ports:
      - '8083:8083'
    command: python3 /tmp/server.py --server "google"
    volumes:
      - ./tests/python/authentication_server:/tmp
    networks:
      cvat:
        aliases:
          - test-google

  github_auth_server:
    image: python:3.9-slim
    restart: always
    ports:
      - '4321:4321'
    command: python3 /tmp/server.py --server "github"
    volumes:
      - ./tests/python/authentication_server:/tmp
    networks:
      cvat:
        aliases:
          - test-github
